name: advent-of-code
version: 0.1.0.0
github: "jbgriesner/advent-of-code-2022"
license: BSD3
author: "JB Griesner"
maintainer: "JB Griesner"
copyright: "2022 JB Griesner"

extra-source-files:
  - README.md

description: Please see the README on GitHub at https://github.com/jbgriesner/advent-of-code-2022

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  advent-of-code-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - text
      - split
