[package]
edition = "2021"
name = "day-11"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = {version = "0.17.7", features = ["rayon"]}
nom = {workspace = true}
rayon = "1.8.0"
