module Days (solve_day1, solve_day2, solve_day3, solve_day4, solve_day5, solve_day6, solve_day7, solve_day8, solve_day9, solve_day10, solve_day11, solve_day12, solve_day13) where

import Day1 (solve_day1)
import Day2 (solve_day2)
import Day3 (solve_day3)
import Day4 (solve_day4)
import Day5 (solve_day5)
import Day6 (solve_day6)
import Day7 (solve_day7)
import Day8 (solve_day8)
import Day9 (solve_day9)
import Day10 (solve_day10)
import Day11 (solve_day11)
import Day12 (solve_day12)
import Day13 (solve_day13)
